### ISSUE TITLE
racer.asd doesn't load subgraph-structure.lisp

### ISSUE THREAD

**Issue by alanruttenberg** [ha-mo-we/Racer#1]
Causes an error when running part of the family.racer example

**Comment by ha-mo-we** [comment]
Dear Alan,

Thank you for pointing out the problems. I'll update the repository really soon.

Best regards,
Ralf

**Comment by ha-mo-we** [comment]
Alan, I updated the repository, and the examples in family.racer seem to work now.
Internal system definitions in racer.asd have been removed.
Note that in the update some improvements to Racer are included as well.
Thanks again for pointing out the problems.

Best regards,
Ralf

**Comment by alanruttenberg** [comment]
Thanks Ralf!
