### ISSUE TITLE
New to racer

### ISSUE THREAD

**Issue by shterman** [ha-mo-we/Racer#11]
Hi,

Looking at the racer user-guide I couldn't understand how to work properly with racer.

I'm working with SBCL, and would like to run racer examples.

Maybe you can help me with those issues please?

**Comment by ha-mo-we** [comment]
Hi,

As a first step, please have a look at the racer/examples/native directory. If you managed to load Racer (e.g., with quicklisp)
you can switch to the package racer-user

? (in-package :racer-user)

Then, load the file family.racer

? (load “<your-directory-goes-here>/familty.racer”)

Aftwards you can have Racer answer your queries as in 

? (concept-subsumes? brother uncle)

See the end of the file family.racer for further examples.

Hope this helps.

Best regards,
Ralf Möller

**Comment by shterman** [comment]
Hi,

First of all thank you very much it has been very helpful.

Still I have few unsolved issues that if you can help me or direct me to some wiki it will be awesome.

I can see in the family example free main parts, if I want to reflect it on a graph:
- ```
       Individuals are the vertexes
  ```
- ```
       Atomic-concepts are the edges
  ```
- ```
       And roles are in order to build the graph
  ```

Am I right? Or totally wrong ☺

Another question is how can I understand each role? Is there specific source file that determine each role and his work?

For example (has-sister :parent has-sibling) , what is the right way to read this role?

Oh and if you can tell me what is the meaning of _top_ in the implications?

Thank you,
Hope to start contributing soon to the repository,
Roy

From: Racer [mailto:notifications@github.com]
Sent: Wednesday, May 04, 2016 3:19 PM
To: ha-mo-we/Racer Racer@noreply.github.com
Cc: Roy Shterman roysh@mellanox.com; Author author@noreply.github.com
Subject: Re: [ha-mo-we/Racer] New to racer (#11)

Hi,

As a first step, please have a look at the racer/examples/native directory. If you managed to load Racer (e.g., with quicklisp)
you can switch to the package racer-user

? (in-package :racer-user)

Then, load the file family.racer

? (load “<your-directory-goes-here>/familty.racer”)

Aftwards you can have Racer answer your queries as in

? (concept-subsumes? brother uncle)

See the end of the file family.racer for further examples.

Hope this helps.

Best regards,
Ralf Möller

> On 04.05.2016, at 12:41, shterman notifications@github.com wrote:
> 
> Hi,
> 
> Looking at the racer user-guide I couldn't understand how to work properly with racer.
> 
> I'm working with SBCL, and would like to run racer examples.
> 
> Maybe you can help me with those issues please?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHubhttps://github.com/ha-mo-we/Racer/issues/11#issuecomment-216842952

**Comment by ha-mo-we** [comment]
Hi Roy,

> On 04.05.2016, at 23:15, shterman notifications@github.com wrote:
> 
> Hi, 
> 
> First of all thank you very much it has been very helpful. 
> 
> Still I have few unsolved issues that if you can help me or direct me to some wiki it will be awesome. 
> 
> I can see in the family example free main parts, if I want to reflect it on a graph: 
> - Individuals are the vertexes 
> - Atomic-concepts are the edges 

Atomic concepts are label for vertices.

> - And roles are in order to build the graph 

Roles are edge labels. Edges are built with role assertions.

> Am I right? Or totally wrong ☺ 
> 
> Another question is how can I understand each role? Is there specific source file that determine each role and his work? 

Please have a look at http://dl.kr.org/courses.html

> For example (has-sister :parent has-sibling) , what is the right way to read this role? 
> 
> Oh and if you can tell me what is the meaning of _top_ in the implications? 

_top_ is the most general atomic concepts, i.e., top subsumes every other atomic concept.

Best regards,
Ralf

> Thank you, 
> Hope to start contributing soon to the repository, 
> Roy 
> 
> From: Racer [mailto:notifications@github.com] 
> Sent: Wednesday, May 04, 2016 3:19 PM 
> To: ha-mo-we/Racer Racer@noreply.github.com 
> Cc: Roy Shterman roysh@mellanox.com; Author author@noreply.github.com 
> Subject: Re: [ha-mo-we/Racer] New to racer (#11) 
> 
> Hi, 
> 
> As a first step, please have a look at the racer/examples/native directory. If you managed to load Racer (e.g., with quicklisp) 
> you can switch to the package racer-user 
> 
> ? (in-package :racer-user) 
> 
> Then, load the file family.racer 
> 
> ? (load “<your-directory-goes-here>/familty.racer”) 
> 
> Aftwards you can have Racer answer your queries as in 
> 
> ? (concept-subsumes? brother uncle) 
> 
> See the end of the file family.racer for further examples. 
> 
> Hope this helps. 
> 
> Best regards, 
> Ralf Möller 
>

**Comment by shterman** [comment]
Hi again,

After reading the stuff you gave me about DL I got a little more 
experienced with the subject but still I have some unsolved issues with 
racer.

If it's ok lets look at a simple example:

(in-knowledge-base data data-mining)

(signature :atomic-concepts (task quality)
                 :roles (has-connection)
                 :individuals (a b c))

(instance a task)

(instance b quality)

(instance c task)

(related a b has-sibiling)

(related b c has-sibiling)

In my understanding we get some graph looks like this:

(a) -----has-connection---->(b)------has-connection---->(c)

I couldn't understand, which query can tell me if (a) has-connection (c),

Also, if there is some available documentation of the queries it will be 
great.

I'm truly trying to understand the architecture of the engine so I could 
contribute code into it.

Thank you very much for everything,

Roy

**Comment by ha-mo-we** [comment]
Hi Roy,

If you want c connected to a in the chain what about defining has-connection to be transitive?

(in-package :racer-user)

(in-knowledge-base test)

(transitive has-connection)

(instance a task)

(instance b quality)

(instance c task)

(related a b has-connection)

(related b c has-connection)

(retrieve (?x)
          (a ?x has-connection))

The latter is a query that returns the following answer

(((?X B)) 
 ((?X C)))

which indicates that there a two possible bindings for ?x namely b and c.

Please note the open-world assumption

(in-package :racer-user)

(in-knowledge-base test)

(related a b r)
(related a c r)

(individual-instance? a (at-least 2 r))  --> nil  (i.e., false)

The latter expression (a query) returns nil since b and c might refer to the same domain objects

(individual-instance? a (at-least 1 r)) --> t  (i.e., true)

(individual-instance? a (at-most 2 r)) --> nil  (What is not stated, i.e., a third r-successor for a, is not necessarily false)

Regards,
Ralf

**Comment by shterman** [comment]
Hi Ralf,

Thanks again for the help,

Actually I read most of the user guide for RacerPro in https://www.ifis.uni-luebeck.de/~moeller/racer/Racer-2.0/users-guide-2-0.pdf
And it really helped, but still I’m missing a point probably.

I want to give an attribute to a specific edge, (a weight of the edge).

Assuming I have rexamples like this

(in-knowledge-base data data)

(signature :atomic-concepts (task quality)
                :roles ((has-con :transitive t)
                        (has-qual :feature t))
                :individuals (a b c)
                :attributes ((real age))
                )
(instance a task)
(instance b quality)
(instance c task)
(instance d task)
(instance e (= age 18))
(related a c has-con (= age 25))
(related c d has-con)

I’m getting an error when trying to assign an age attribute to the relation between a c has-con, is there any proper way to do it?

Thanks,
Roy

**Comment by ha-mo-we** [comment]
Hi Roy,

Sorry for the delay. Your email got misplaced.

As I understand, you would like to add an attribute to a binary relation (has-con),
essentially treating has-con as a ternary relation. While this make perfect sense
in relational databases, description logics provide only binary relations, thus 
avoiding all kinds of problems about normalization and the like.

Best regards,
Ralf

**Comment by nicemathew53** [comment]
how to switch to the package racer-user?

**Comment by ha-mo-we** [comment]
Please have a look at the following examples. ? is the prompt of the Lisp system. Type in the expressions from family.racer.
Best regards,
Ralf

Welcome to Clozure Common Lisp Version 1.11-store-r16714  (DarwinX8664)!

CCL is developed and maintained by Clozure Associates. For more information
about CCL visit http://ccl.clozure.com.  To enquire about Clozure's Common Lisp
consulting services e-mail info@clozure.com or visit http://www.clozure.com.

? (ql:quickload "racer")
To load "racer":
  Load 1 ASDF system:
    racer
; Loading "racer"
.
("racer")
? (in-package :racer-user)
#<Package "RACER-USER">
? (load "~/Desktop/family.racer")
;Loading #P"/Users/rm/Desktop/family.racer"...
#P"/Users/rm/Desktop/family.racer"
? (concept-subsumes? brother uncle)

Concept (PARENT) causes a cycle in TBox FAMILY
T
? (concept-ancestors mother)

((WOMAN) (PARENT) (PERSON) (*TOP* TOP) (HUMAN))
? (concept-descendants man)
((*BOTTOM* BOTTOM) (UNCLE) (BROTHER) (FATHER))
? (all-transitive-roles)
((INV HAS-DESCENDANT) HAS-DESCENDANT)
? (individual-instance? doris woman)
T
? (individual-types eve)
((SISTER) (WOMAN) (PERSON) (HUMAN) (*TOP* TOP))
? (individual-fillers alice has-descendant)
(CHARLES EVE DORIS BETTY)
? (individual-direct-types eve)
((SISTER))
? (concept-instances sister)
(EVE DORIS BETTY)
?
