### ISSUE TITLE
i donot know anything about racerpro

### ISSUE THREAD

**Issue by nicemathew53** [ha-mo-we/Racer#14]
i am using  ubuntu . i try to load  example ,it loading but while i was try to execute example query it shows nil results only. i tried with  familiy.racer example it shows nil

**Comment by gschadow** [comment]
Much too generic a problem description. You'd have to show exactly what it is you're doing for anyone to comment.

**Comment by arademaker** [comment]
I suggest close this kind of issue, it is almost a spam
