### ISSUE TITLE
Does not build with sbcl 1.4.10 - type inference problem

### ISSUE THREAD

**Issue by quicklisp** [ha-mo-we/Racer#15]
I get this:

    ; file: /home/quicklisp/quicklisp-controller/dist/build-cache/racer/892f63e2bc25b640d933ba9855e71de3b7fbc3aa/racer-20180726-git/source/label-info-structures.lisp
    ; in: DEFUN COPY-LABEL-INFO
    ;     (RACER::COPY-INVERSE-LABEL-INFO RACER::LABEL-INFO)
    ; 
    ; note: deleting unreachable code
    ; 
    ; caught WARNING:
    ;   Derived type of LABEL-INFO is (VALUES (NOT BASIC-LABEL-INFO) &OPTIONAL), conflicting with its asserted type RACER::INVERSE-LABEL-INFO.
    ;   See also:
    ;     The SBCL Manual, Node "Handling of Types"

Full log: http://report.quicklisp.org/2018-07-27/failure-report/racer.html#racer

**Comment by ha-mo-we** [comment]
Will check

rm

**Comment by ha-mo-we** [comment]
I think I found the problem. Need to run the test suite though.

rm

**Comment by ha-mo-we** [comment]
Should work with latest version on Git. Thank you for pointing out the problem.

BR
Ralf
