### ISSUE TITLE
Source for system racer-test seems to be missing

### ISSUE THREAD

**Issue by alanruttenberg** [ha-mo-we/Racer#2]
(asdf:defsystem "racer-test"
  :description "Test support for RACER"
  :license "BSD 3"
  :pathname #P"racer:tests;"
  :serial t
  :depends-on ((:require "racer"))
  :components ((:file "test-support")
               (:file "test-kb-support")
               (:file "owl-tests")
               (:file "owlapi-tests")
               (:file "test-queries")
               (:file "test-test-tboxes")))

**Comment by ha-mo-we** [comment]
Too bad, somehow the system definition for “racer-test” made it into the racer.asd file.
We’ll remove it in the next version.
