### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [ha-mo-we/Racer#3]
Please consider adding :description, :author and :license information to your ASDF system. This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by ha-mo-we** [comment]
> On 31.05.2015, at 22:15, David Chkhikvadze notifications@github.com wrote:
> 
> Please consider adding :description, :author and :license information to your ASDF system. This will greatly help Quicklisp users and make it easier for them to report bugs.

OK, will add more details in the next release.

Regards,
Ralf
