### ISSUE TITLE
SBCL 1.2.13

### ISSUE THREAD

**Issue by arademaker** [ha-mo-we/Racer#4]
After correctly load with `(ql:quickload :racer)` I got the error below when I tried to run

```
(racer:racer-toplevel)
```

```
The function RACER:RACER-TOPLEVEL is undefined.
   [Condition of type UNDEFINED-FUNCTION]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1006048003}>)

Backtrace:
  0: (SYMBOL-FUNCTION RACER:RACER-TOPLEVEL)
  1: (SB-INT:SIMPLE-EVAL-IN-LEXENV (RACER:RACER-TOPLEVEL) #<NULL-LEXENV>)
```

```
CL-USER> *features*
(:FLEXI-STREAMS :ASERVE :HTMLGEN :ACL-COMPAT :CL-FAD :BORDEAUX-THREADS
 :CL-PPCRE :THREAD-SUPPORT :ONLY-RUNTIME-EVALUATION :NRQL-ERROR-HANDLER
 :OWL-DATATYPE-SUPPORT :ONLINEDOC :RACER :RACER-SERVER :SWANK :QUICKLISP
 :ASDF-PACKAGE-SYSTEM :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-MACOSX :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ALIEN-CALLBACKS :ANSI-CL
 :ASH-RIGHT-VOPS :BSD :C-STACK-IS-CONTROL-STACK :COMMON-LISP
 :COMPARE-AND-SWAP-VOPS :COMPLEX-FLOAT-VOPS :CYCLE-COUNTER :DARWIN
 :DARWIN9-OR-BETTER :FLOAT-EQL-VOPS :GENCGC :IEEE-FLOATING-POINT
 :INLINE-CONSTANTS :INODE64 :INTEGER-EQL-VOP :INTERLEAVED-RAW-SLOTS
 :LINKAGE-TABLE :LITTLE-ENDIAN :MACH-EXCEPTION-HANDLER :MACH-O
 :MEMORY-BARRIER-VOPS :MULTIPLY-HIGH-VOPS :OS-PROVIDES-BLKSIZE-T
 :OS-PROVIDES-DLADDR :OS-PROVIDES-DLOPEN :OS-PROVIDES-PUTWC
 :OS-PROVIDES-SUSECONDS-T :PACKAGE-LOCAL-NICKNAMES :PRECISE-ARG-COUNT-ERROR
 :RAW-INSTANCE-INIT-VOPS :SB-AFTER-XC-CORE :SB-CORE-COMPRESSION :SB-DOC
 :SB-EVAL :SB-LDB :SB-PACKAGE-LOCKS :SB-SIMD-PACK :SB-SOURCE-LOCATIONS :SB-TEST
 :SB-THREAD :SB-UNICODE :SB-XREF-FOR-INTERNALS :SBCL
 :STACK-ALLOCATABLE-CLOSURES :STACK-ALLOCATABLE-FIXED-OBJECTS
 :STACK-ALLOCATABLE-LISTS :STACK-ALLOCATABLE-VECTORS
 :STACK-GROWS-DOWNWARD-NOT-UPWARD :SYMBOL-INFO-VOPS :UD2-BREAKPOINTS :UNIX
 :UNWIND-TO-FRAME-AND-CALL-VOP :X86-64)
```

Any idea?

**Comment by ha-mo-we** [comment]
racer:racer-toplevel is not supprted for SBCL.

"In order to start the Racer server using ACL, CCL, or LW, just execute (racer:racer-toplevel)”

We should problaby mention this explicitly.

Best regards,
Ralf

**Comment by fcbr** [comment]
Hello Ralf,

I am interesting in adding support for SBCL; would you kindly give and overview what you think needs to be done?

Cheers,
Fabricio

**Comment by binghe** [comment]
SBCL compiler cannot compile Wilbur RDF (part of Racer), which has complicated macro expansions. On the other side, Racer client doesn't use Wilbur code at all, so it supports SBCL well.

I think people with deep knowledge on Wilbur may figure out how to fix Wilbur to support SBCL, then the whole Racer Server could run in SBCL too. (I'm trying)

**Comment by arademaker** [comment]
@binghe wilbur is already available in quicklisp and loadable in SBCL!

**Comment by ha-mo-we** [comment]
The one that comes with Racer includes some changes. I sent the changes to Ora Lassila but I am not sure 
whether they made it into the Quicklisp distribution. Thus, Racer cannot directly use the version provided
by Quicklisp directly.

-Ralf

**Comment by arademaker** [comment]
@ha-mo-we thanks for the explanation. I believe the changes that you submitted to Ora Lassila could be submitted as PR to https://github.com/lisp/de.setf.wilbur. This is the code distributed in Quicklisp.

**Comment by ha-mo-we** [comment]
Hi Alexandre, I think I should remove better remove all RDF stuff (including OWL) from the Racer core.

The problem with Wilbur as provided at https://github.com/lisp/de.setf.wilbur is that the asd loads 
not only the core engine, which we need, but also a query interface for RDF graphs as well as some 
goodies, the latter of which will fit almost nowehere, the former of which shows not-so-impressive performance.
Wilbur should be stripped down such that only the core facilities for building RDF graphs are provided.

Then, using Wilbur core, it would make sense to provide a Racer submodule (possibly loadable on demand)
that Wilbur core from Github/Quicklisp to make Racer load RDF/OWL files as before.

Regards,
Ralf

**Comment by arademaker** [comment]
@ha-mo-we sorry for this late reply, I just got a message in my inbox asking about this issue. That situation that you describe suggests an excellent project for a student on improving the modularity of Wilbur and Racer2. It is a shame how the support of RDF and OWL for Lisp is so behind of the libraries available in other languages such as Python etc.

Do you agree? Is there a concrete plans for Racer2 new improvements?

**Comment by arademaker** [comment]
@ha-mo-we maybe it can be useful to provide a step-by-step sample section in the readme. For me, the lracer only started in SBCL with additional heap space:

```
$ sbcl --dynamic-space-size 2GB
This is SBCL 1.4.3, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload :lracer)
To load "lracer":
  Load 1 ASDF system:
    lracer
; Loading "lracer"
..................................................
..................................................
.............
(:LRACER)
*
```

Moreover, I didn't really understand the paragraph:

> Racer has been tested with ACL 8.2, CCL 1.9, LW 6.1, and SBCL 1.1.8. All Racer forms are available from the package racer. See the doc directory for a User's Guide and a Reference Manual. In order to start the Racer server using ACL, CCL, or LW (sorry not for SBCL), just execute (racer:racer-toplevel)

Is it possible to use Racer not as a client-server application? If not, does it make any sense talk about SBCL in this paragraph? We could have a more explicit mention to: (1) the SERVER code compatible with ACL, CCL and LW; (2) the client lracer that is also compatible with SBCL besides ACL, CCL and LW. Am I right?    

Section 1.1.1 from the User Guide says:

> RacerPro is available as a server version (RacerPro Server) with APIs e.g. for Java or Common Lisp. RacerPro communicates with client programs via various interfaces, either RacerPro-specific ones (maximum expressivity) or standardized ones (maximum portability).
