### ISSUE TITLE
Protégé plugin

### ISSUE THREAD

**Issue by fcbr** [ha-mo-we/Racer#5]
Would it be possible to release the source for the Protégé plugin that used to be at http://www.racer-systems.com/protege/readme.html ?

**Comment by ha-mo-we** [comment]
Dear Fabricio,

I will check out whether we can make the sources available.

Best regards,
Ralf

**Comment by csnyulas** [comment]
A Protégé user was also looking for the availability of the RacerProTG plug-in, and when I tried to point her to a .zip file that she could download, I realized that I could not find any place, where it can be downloaded from.
Conform to the README.md, the Protégé plug-in code is in the [racer-owlapi/trunk/protege](https://github.com/ha-mo-we/Racer/tree/master/racer-owlapi/trunk/protege).
Is that complete and is supposed to be working?
Could it be released as a standalone package, for people who can't build it for themselves? 
It would be really nice if people could install and use this plug-in out of the box, just like other reasoner plug-ins, without too much hassle. I think the Protégé community would really appreciate it.
We could then also update the [Protégé plugin's wiki page](http://protegewiki.stanford.edu/wiki/RacerProTG).

**Comment by ha-mo-we** [comment]
I am afraid, the RacerPro plugin was provided for Protege 4, and it is rather certain that adapting it to Protege 5 will require some work.

Ralf

**Comment by csnyulas** [comment]
The person who asked about the RacerProTG plug-in was planning to use it with Protege 4.1. It would be really great, if such people would have a place to go, from where they could simply download the plugin, which they could then easily install and use.

Once this is available, maybe some people from the community would be motivated to help in the adaptation of the plug-in to Protege 5.x. If I remember well other reasoner plugins (such as Hermit, Fact++, Pellet) were fairly quickly adapted to Protege 5. One could take a look at what changes their developers needed to do make in this process, to get a better sense for how much effort would it take to do the same for RaceProTG.
