### ISSUE TITLE
(check-abox-coherence) returns (NIL NIL)

### ISSUE THREAD

**Issue by fcbr** [ha-mo-we/Racer#7]
Not sure I understood this one:

```
CL-USER> (check-abox-coherence)
(NIL NIL)
```

Shouldn't the second argument be one explanation for the inconsistency?  Is this due to some out of memory condition? (My ontology contains a couple of million triples.)  Or am I missing some initialization steps?

**Comment by fcbr** [comment]
It looks like it was something related to encoding; I changed the server encoding to UTF8 and it showed the explanation.  I'll close the issue.

**Comment by fcbr** [comment]
Oops, it wasn't the encoding, but UNA.  With UNA set to true I get an explanation; otherwise I get NIL.

**Comment by ha-mo-we** [comment]
Hi Fabricio,

If you send me you abox (or a subset of it that shows the error) and the respective calls that produce the error, I can certain try to fix it.

Best regards,
Ralf

> No sure I understood this one:
> 
> CL-USER> (check-abox-coherence)
> (NIL NIL)
> Shouldn't the second argument be one explanation for the inconsistency? Is this due to some out of memory condition? (My ontology contains a couple of million triples.) Or am I missing some initialization steps?

It looks like it was something related to encoding; I changed the server encoding to UTF8 and it showed the explanation. I'll close the issue.

**Comment by fcbr** [comment]
I'll try to come up with a smaller data set and also a reliable way of reproducing it (so far it has been a bit inconsistent in the results, so I don't even thing it has anything to do with UNA anymore).  Thanks.

**Comment by arademaker** [comment]
Anyway, the data that we are working on is https://github.com/own-pt/openWordnet-PT. The TBOX is the wn30.ttl file. The ABOX is composed by files wordnet-en.nt.gz and own-pt.nt.gz.

**Comment by gschadow** [comment]
I also get (NIL NIL), I thought that was normal. When I had a satisfiability issue, it was shown there instead of (NIL NIL). Anyway, I also wrote my own satisfiability checker:

```
(defun check-satisfiable (&optional (concepts (all-atomic-concepts)))
  (cond 
    ((eq concepts nil) nil)
    (t ((lambda (concept)
          (cond
            ((or (eq concept 'bottom)
                 (concept-satisfiable-p concept 'default))
             (check-satisfiable (cdr concepts)))
            (t (cons (car concepts)
                     (check-satisfiable (cdr concepts)))))) (car concepts)))))
```
Oh and to be sure, I am working directly in SBCL (in-package "RACER-USER"), not in some server or limited racer-toplevel.
