### ISSUE TITLE
Racer with Allegro Graph: illegal operator error condition

### ISSUE THREAD

**Issue by fcbr** [ha-mo-we/Racer#8]
I'm trying to use Racer with Allegro Graph 5.1 running locally, but when I issue (open-triple-store "wn30"), I get an error saying "illegal operator".  I tried specifying the `:directory` key as well, but it still gives me the error.

Racer is running under Allegro Lisp (mlisp) 9.0, while LRacer is running under SBCL 1.2.13.

This is the server output with `-debug` on:

```
(open-triple-store "wn30")

An error condition has been signalled (debug handler): Illegal
                                                       operator
                                                       in
                                                       (open-triple-store
                                                        wn30)
```

**Comment by ha-mo-we** [comment]
Hi Fabricio,

The open source version of Racer does not support triple store access with open-triple-store. With AllegroGraph 3 there was an Allegro triple store included in the RacerPro executable, i.e., AG3 was provided as fasl files, and we were allowed to include them in RacerPro. Later, with AG4, Franz switched to a server model for AG (fasls were not provided any longer). We cannot provide AG3 fasl files as part of the open source version of Racer (wouldn’t work with SBCL BTW).

If you use AG5 why don’t you just send a SPARQL query to AG to retrieve tuples, store them as RDF/XML, and use owl-read-file to read the descriptions into a tbox/abox pair?

All the best,
Ralf

**Comment by fcbr** [comment]
Thanks for the clarification.  I'm doing that, but I am finding the loading via `owl-read-file` too slow (almost 1h to load around 4M triples) so I was looking for faster alternatives.  I'll close the issue.
