### ISSUE TITLE
LRacer: cannot run under CCL or Allegro Lisp (only SBCL)

### ISSUE THREAD

**Issue by fcbr** [ha-mo-we/Racer#9]
For some reason, I can only execute `lracer` commands sucessfully if I use SBCL.

Using Allegro Lisp 9.0, the packge LRacer doesn't compile (via `quicklisp`):

```
cl-user(1): (ql:quickload :lracer)
To load "lracer":
  Load 1 ASDF system:
    lracer
; Loading "lracer"
; While file-compiling #'"lracer-reader-macros.lisp" in
#P"/home/fcbr/repos/Racer/clients/lracer/lracer-reader-macros.lisp"
; starting at file character position 1279:
Error: Package "stream" not found. [file position = 1500]
  [condition type: reader-error]
```

Using CCL 1.10 it compiles and loads okay, but any command that I issue is met with an exception of type `LRACER-CONNECTION-ERROR`.

```
? (owl-open-file "...")
> Error: LRACER-CONNECTION-ERROR: LRacer cannot connect to Racer.
> While executing: RACER::SERVICE-REQUEST, in process listener(1).
  0: (RACER::SERVICE-REQUEST "(owl-read-file \"/home/fcbr/work/wn/verification/correct/complete.rdf\")" :HOST "127.0.0.1" :PORT 8088 :SNA-ERROR-P T :SNA-VALUE :NO-CONNECTION)
  1: (OWL-READ-FILE "/home/fcbr/work/wn/verification/correct/complete.rdf" :VERBOSE NIL :INIT NIL :KB-NAME NIL :LOCATOR NIL :RECURSIVE NIL :IGNORE-IMPORT NIL :IMPORT-META-ONTOLOGIES NIL :EXCLUDED-META-ONTO..
  2: (CCL::CALL-CHECK-REGS OWL-READ-FILE "/home/fcbr/work/wn/verification/correct/complete.rdf")
  3: (CCL::CHEAP-EVAL (OWL-READ-FILE "/home/fcbr/work/wn/verification/correct/complete.rdf"))
```

**Comment by ha-mo-we** [comment]
Hi Fabricio,

> On 25.08.2015, at 14:55, Fabricio Chalub notifications@github.com wrote:
> 
> For some reason, I can only execute lracer commands sucessfully if I use SBCL.
> 
> Using Allegro Lisp 9.0, the packge LRacer doesn't compile (via quicklisp):
> 
> cl-user(1): (ql:quickload :lracer)
> To load "lracer":
>   Load 1 ASDF system:
>     lracer
> ; Loading "lracer"
> ; While file-compiling #'"lracer-reader-macros.lisp" in
> #P"/home/fcbr/repos/Racer/clients/lracer/lracer-reader-macros.lisp"
> ; starting at file character position 1279:
> Error: Package "stream" not found. [file position = 1500]
>   [condition type: reader-error]

I currently have not access to ACL.
You could try evaluating (require ':streamc) before working with lracer.

> Using CCL 1.10 it compiles and loads okay, but any command that I issue is met with an exception of type LRACER-CONNECTION-ERROR.

Unfortunately I forgot ccl in lracer. Please find an update in the attachment.

Best regards,
Ralf

**Comment by fcbr** [comment]
Thanks, I was able to run lracer under CCL now.  I will see if I can make it run under `mlisp` and report back.
